### ISSUE TITLE
Miner stop automatic

### ISSUE THREAD

**Issue by chitkiu** [felixbrucker/miner-manager#2]
Hi, I have a problem. When I start miners, it starts to work, but then stops automatically. 
Console in browse: 

> POST http://IP:8082/api/mining/start net::ERR_CONNECTION_REFUSED

and 

> GET http://IP:8082/api/mining/stats net::ERR_CONNECTION_REFUSED

In pm2 log:

> 0|miner-ma | [2018-02-08 17:20:59.578] [INFO] config - initializing, please wait...
> 0|miner-ma | [2018-02-08 17:20:59.657] [INFO] system - server running on port 8082
> 0|miner-ma | [2018-02-08 17:21:00.619] [INFO] mining - autostart enabled, starting miner shortly..
> 0|miner-ma | [2018-02-08 17:21:10.621] [INFO] mining - starting up miners, please wait..
> 0|miner-ma | [2018-02-08 17:21:10.630] [INFO] mining - [claymore-eth] miner started
> 0|miner-ma | [2018-02-08 17:21:12.736] [INFO] mining - [claymore-eth] miner stopped
> 0|miner-ma | [2018-02-08 17:21:12.736] [INFO] mining - all miners stopped
> 0|miner-ma | [2018-02-08 17:21:13.083] [INFO] config - initializing, please wait...
> 0|miner-ma | [2018-02-08 17:21:13.172] [INFO] system - server running on port 8082
> 0|miner-ma | [2018-02-08 17:21:14.130] [INFO] mining - autostart enabled, starting miner shortly..

It's only when use claymore-eth

**Comment by felixbrucker** [comment]
does this happen as well when running it without pm2?

**Comment by felixbrucker** [comment]
from to logs it seems as if after starting claymore-eth the miner-manager exits and thus shuts down all miners, pm2 then respawns it

**Comment by chitkiu** [comment]
I don't try. Thanx.
I'll try and write tomorrow :smile:

**Comment by felixbrucker** [comment]
No problem, also whats your nodejs version?

**Comment by chitkiu** [comment]
8.9.4

**Comment by chitkiu** [comment]
Okey, when I run without pm2 all work nice

**Comment by felixbrucker** [comment]
Are you using windows or linux?
Do you mind sharing your settings.json (with sensitive information removed)?

I couldn't reproduce the issue with pm2 on my windows machine yet

**Edit:** seeing the commits you made in your fork repo indicates you are using a custom folder inside this directory to store miner binaries, is that correct? If so it would explain the restarts:
the pm2 process.json includes a watch property and an exclude property to watch for changes made inside the directory recursively. I excluded my default dirs. Once pm2 detects that claymore-eth has started to write its log file it restarts miner-manager.

**Comment by chitkiu** [comment]
Thanx, I turn off log file at Claymore and all good :+1: :smiley: 
And I use linux.

**Comment by felixbrucker** [comment]
Thanks, good to know!
You can put your custom directory in the `ignore_watch` array in `process.json` and everything should work even with logs
